# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20171128_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Mediocre'), (4, 'Good'), (5, 'Awesome')], null=True),
        ),
    ]
