# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20171130_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='features',
            field=models.ManyToManyField(blank=True, to='hotels.Feature'),
        ),
    ]
