# Generated by Django 2.0 on 2017-12-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20171130_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Country'),
        ),
        migrations.AlterField(
            model_name='room',
            name='frees_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Hotel'),
        ),
    ]
